### ISSUE TITLE
Update python versions

### ISSUE THREAD

**Issue by flying-sheep** [readthedocs/readthedocs-docker-images#138]
Hi! Our docs break because of a bugfix that lives in Python 3.7.6 and 3.8.1. You’re using pretty old Python versions:

https://github.com/readthedocs/readthedocs-docker-images/blob/6e61b2a903a0a22d2c14bec5f55b01467c39fbda/Dockerfile#L151-L152

Is there a reason why the Python patch versions aren’t kept up to date? They’re super stable. In 10 years of Python coding I never had a single issue arising from a too-new patch release.

TBH it didn’t even occur to me that both Travis and RTD could possibly not update the Python versions as they drop.

**Comment by humitos** [comment]
Thanks for pointing this out. 

> Is there a reason why the Python patch versions aren’t kept up to date?

Basically, it's time and effort that doesn't have rewards usually... Until someone hit an issue with this :smile: 

@flying-sheep what's your project URL just to take a look (and a building URL that fails because of this problem)?

I'll see if I can include the newest patch versions in the Docker images we currently have in production.

**Comment by flying-sheep** [comment]
There’s some investigation done here: https://github.com/theislab/scanpydoc/pull/20#issuecomment-698861767

You can see it in action e.g. in this build: https://travis-ci.com/github/theislab/scanpydoc/jobs/390871698
