### ISSUE TITLE
Upgrade conda?

### ISSUE THREAD

**Issue by astrojuanlu** [readthedocs/readthedocs-docker-images#173]
> Do you take patches to upgrade Conda to 4.10.x? I see there is a comment about memory usage in Conda 4.7.12.1 and since then there were a number of performance improvements.

_Originally posted by @jezdez in https://github.com/numba/numba/issues/7182#issuecomment-874631554_

It is unlikely that we will rebuild our `stable` and `latest` images, because that would break lots of builds. We are working on [an alternative scheme](https://docs.readthedocs.io/en/stable/development/design/build-images.html) but we haven't started with the implementation yet. In the meantime, we could update conda in our `testing` image to something more recent, but at the same time, we are internally debating whether to do a more widespread mamba rollout, since it is faster and consumes less RAM.

Thoughts @readthedocs/core ?

**Comment by jezdez** [comment]
That's fair, I'd support an upgrade in testing to test if the speed/memory usage is still as high now. You're running 4.6.1 IIRC and Conda's latest release is 4.10.x. We could fallback to Mamba otherwise until the new alternative scheme is implemented and shipped. My reasoning to try Conda again is basically to make sure the Conda community is getting what they are expecting and reduce the risk having to deal with subtle implementation differences between Mamba and Conda.

As to using Mamba for all of RTD, I should note that Anaconda and a few other community members like @wolfv and me are currently ramping up work on Conda on making Conda's solver pluggable to use Mamba solver instead. That is one of many new initiatives to breath life into the Conda Open Source project again and better cater to Conda users, commercial or community-based.

**Comment by humitos** [comment]
> You're running 4.6.1 IIRC and Conda's latest release is 4.10.x.

For some reason, the latest release of miniconda is 4.9.2: https://docs.conda.io/en/latest/miniconda.html#linux-installers

I also checked https://repo.anaconda.com/miniconda/ and I found that there is a 4.10.x version but it's not available for `x86_64`. So, I'm upgrading to 4.9.2 in #174 for now. @jezdez is that enough?

**Comment by astrojuanlu** [comment]
We upgraded Miniconda3 to 4.9.2 in #174, closing!
