### ISSUE TITLE
`readthedocs/build:latest` is outdated

### ISSUE THREAD

**Issue by akihironitta** [readthedocs/readthedocs-docker-images#186]
### Report
`readthedocs/build:latest` that is available on [hub.docker.com](https://hub.docker.com/r/readthedocs/build/tags) was pushed at Feb 18, 2020 at 10:49 am and is very outdated.

### Question
With our configuration, which docker image is used by the readthedocs with our configuration?
Is it one of the images that are publicly available on [hub.docker.com](https://hub.docker.com/r/readthedocs/build/tags) or somewhere else?

```yml
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
```
https://github.com/Lightning-AI/lightning/blob/61c28cb428a13c2aea6d7f3f55e0f00431a4ea4e/.readthedocs.yml#L41-L48

### Background
We've been using `readthedocs/build:latest`, but we've recently observed that building our docs fails only in our CI (https://github.com/Lightning-AI/lightning/pull/13547), and thus, we'd like to use one of your docker images to build the docs in our CI to avoid potential issues that may raised by any difference in the environment between our CI and readthedocs' CD although I'm aware that it's not meant to be used for building our docs as stated in your README:

> These images are only for internal usage on Read the Docs project. They are not meant to build your documentation locally, to replace Read the Docs' service or to emulate it locally.

**Comment by humitos** [comment]
Hi, the following configuration

> build: 
>   os: ubuntu-20.04

will use this Docker image currently https://hub.docker.com/layers/build/readthedocs/build/ubuntu-20.04-2022.02.16/images/sha256-cbe6e6e8339567e6e38fb612feee7f73ae15d1684ec241b565af73e740dbcfb6?context=explore

> we'd like to use one of your docker images to build the docs in our CI to avoid potential issues that may raised by any difference in the environment between our CI and readthedocs' CD

Instead of doing this, you can just enable the PR builder in your project and let Read the Docs to build your project on each PR, reporting the status back to GitHub and blocking the merge if it fails for any reason. This way, there won't be surprises when merging the PR into the main branch. Take a look at https://docs.readthedocs.io/en/stable/pull-requests.html

**Comment by ascillitoe** [comment]
Hi @humitos. The PR builder works great for us for the [alibi](https://github.com/SeldonIO/alibi) and [alibi-detect](https://github.com/SeldonIO/alibi-detect) libraries, and is very helpful in allowing us to preview the rendered docs. However, we also build the docs manually in our own CI because we need to check the PDF build passes. This CI has recently been failing since `ubuntu-18.04` [is being deprecated](https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/) as a GitHub runner.

It would be great if the PR builder could add inbuilt support for other builds apart from HTML, but in the mean time, is there anywhere we can access a more recent image? Or is there another recommended approach to test non-html builds in CI?

Thanks in advance!
